### ISSUE TITLE
Probable misbehavior for invalid position

### ISSUE THREAD

**Issue by BenWiederhake** [rbxb/place#1]
https://github.com/rbxb/place/blob/50771a1c0f070d1a01c9c49043585897d3219aa8/server.go#L186

I believe the correct approach would be:

```
if 0 > x || x >= width || 0 > y || y >= height {
	return false
}
```

**Comment by rbxb** [comment]
Yes! Looks like a relic from me moving the successful path from inside the if statement to outside.
