### ISSUE TITLE
Mobile phone

### ISSUE THREAD

**Issue by Malta112** [rbxb/place#10]
So, its working ok on my mobile phone but when i use my fingers to zoom it stops working i have to zoom out is it possible to make it so that if you zoom with you fingers the canvis is zoomed in and not the whole site?
You know what i mean???

**Comment by rbxb** [comment]
It would take a lot more work to add this feature which is why I decided to just use the + and - buttons. I don't plan on changing this right now.

**Comment by Malta112** [comment]
ok and what is with a easy color picker? like the litte sign where you see you selected color and when you click it you can choose a color?

**Comment by rbxb** [comment]
You can enter the hex value of the color that you want to use. Here is a website that will help you get a color hex value: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Colors/Color_picker_tool

**Comment by Malta112** [comment]
yeah i know but i planed to use it in my class and not all of them know how and it was just a question

**Comment by rbxb** [comment]
I can add a popup that displays information about the controls.

**Comment by Malta112** [comment]
that would help

**Comment by rbxb** [comment]
Added a help popup

**Comment by rbxb** [comment]
Also added pinch to zoom.
