### ISSUE TITLE
Is it ok if I use place for a project I want to make?

### ISSUE THREAD

**Issue by ghost** [rbxb/place#12]
So i was planning to make a multiplayer pixel canvas project and so I just wanna know if I can use yours if it's ok, I will also credit you if needed. Thanks.

**Comment by rbxb** [comment]
Please see the [license](https://github.com/rbxb/place/blob/master/LICENSE). You may use this code in your own project for whatever you want so long as the project that you make is also open source.

**Comment by ghost** [comment]
> Please see the [license](https://github.com/rbxb/place/blob/master/LICENSE). You may use this code in your own project for whatever you want so long as the project that you make is also open source.

Ok so I don't want to get copyrighted, so if I use your place for a project I want to make and I also will fully credit you it's ok right? And it is open source...

**Comment by rbxb** [comment]
If the code for your project is made available then you can use it for whatever your want.

I'm don't really care what you do with the code in this project and I'm not going to hunt anyone down for not following the license. I just want to encourage people to open source their code.

**Comment by ghost** [comment]
> 

Ok thank you 🤗
