### ISSUE TITLE
How do i port forward this?

### ISSUE THREAD

**Issue by inkstray** [rbxb/place#19]
I tried port forwarding directly through router settings but it doesnt seem to work
i dont even know what options to use aswell as what to edit in the js file

**Comment by rbxb** [comment]
In place.js you need to modify the constants at the top (LOCAL_MODE and LOCAL_IP_ADDRESS) depending on whether you are hosting the server locally or with a public facing IP.

To get a public facing IP you would have to talk to your internet provider or you could host the server on a cloud platform. I use a DigitalOcean Droplet to host my instance of Place.

**Comment by true-king-al** [comment]
> 

uhh you removed the local mode and local IP address so what do I do now?
