### ISSUE TITLE
Stuck on connecting

### ISSUE THREAD

**Issue by Denisqvx** [rbxb/place#21]
Everything works fine till I connect to the localhost port then it strikes me with the connecting.., which never connects at all. 
![image](https://user-images.githubusercontent.com/77736799/225063075-5329eed3-8b08-4fe5-b390-57ca6919ab6e.png)

**Comment by Denisqvx** [comment]
This is happening in the dev console, I cannot understand it and I'm trying to figure out the cause. 
![image](https://user-images.githubusercontent.com/77736799/225066506-f13e0ea0-e737-42f1-9235-02a0c10bf73e.png)

**Comment by rbxb** [comment]
I just pushed a change that should fix this. You won't need to mess with LOCAL_MODE anymore. It should just work when you pull it.
