### ISSUE TITLE
Disabling or reducing rate limit to enable click and drag drawing

### ISSUE THREAD

**Issue by rosebrt** [rbxb/place#22]
I added a dragdraw variable in the js to implement some pretty simple "click and drag draw" functionality, only problem is that it keeps kicking me for rate limit. I tried changing the rate limit values, and even just forcing the rate limit function to always return false, but it still kicks me.

**Comment by rosebrt** [comment]
Sorry I'm a moron I just needed to rebuild

**Comment by shakyevan444** [comment]
may i ask how could i add this dragging feature
