### ISSUE TITLE
Painting pixels not working?

### ISSUE THREAD

**Issue by cckelly** [rbxb/place#3]
Painting pixels doesn't seem to be working, not sure if it was turned off. Very cool stuff btw!

**Comment by rbxb** [comment]
As far as I can tell it is working in the live version. Is it still not working for you?

**Comment by cckelly** [comment]
Unfortunately not - is there a hotkey? Doesn't seem like it looking at the code, I've tried on Chrome on my laptop and phone.

**Comment by rbxb** [comment]
That's weird. It is currently working for me. Do you get an error when you load the page? Are there errors in the JavaScript console?

**Comment by cckelly** [comment]
No errors in console, everything renders okay. Version 99.0.4844.74 (Official Build) (x86_64) is the version of Chrome I'm using. I tried Safari too and it didn't work - you're on Chrome?

**Comment by rbxb** [comment]
It works on Firefox and Chrome for me. Are you using right-click to draw?

**Comment by cckelly** [comment]
Well now I feel silly, I was just left-clicking like a noob, thanks!
