### ISSUE TITLE
how do I run it

### ISSUE THREAD

**Issue by Baggette** [rbxb/place#4]
how do I run this on ubuntu server 20

**Comment by rbxb** [comment]
You need to compile [this](https://github.com/rbxb/place/tree/master/cmd/place
) Go program yourself.

Then run it and set the -root argument to the path to the web/root directory.  
e.g. `place -root ./place/web/root`

You can run `place -help` to get the full list of options.

**Comment by thatretrodev** [comment]
I actually had the same problem a few months ago - I didn't understand how to correctly self-host pl/ace

**Comment by Baggette** [comment]
> You need to compile [this](https://github.com/rbxb/place/tree/master/cmd/place) Go program yourself.
> 
> Then run it and set the -root argument to the path to the web/root directory. e.g. `place -root ./place/web/root`
> 
> You can run `place -help` to get the full list of options.

**how** do I compile it?

**Comment by tchereau** [comment]
> > You need to compile [this](https://github.com/rbxb/place/tree/master/cmd/place) Go program yourself.
> > Then run it and set the -root argument to the path to the web/root directory. e.g. `place -root ./place/web/root`
> > You can run `place -help` to get the full list of options.
> 
> **how** do I compile it?

go build cmd/place/main.go

**Comment by tchereau** [comment]
> I actually had the same problem a few months ago - I didn't understand how to correctly self-host pl/ace

at _filters.txt 
#serve
        ace desktop.html
#place ws
#place place.png
#place stat%         

ace call the desktop.html file
