### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by lucislucbutnotluc** [rbxb/place#41]
I would like to see support for linux if you'd be able to do that...

**Comment by rbxb** [comment]
It will work on Linux as is

**Comment by lucislucbutnotluc** [comment]
Oh, I haven't figured out how to start it then.. Is it listed in the tutorial here?

**Comment by rbxb** [comment]
The instructions in README should work for any platform. What part are you stuck at?

**Comment by lucislucbutnotluc** [comment]
Must've read it wrong, i'll read through it again and tell you if I run into issues..
