### ISSUE TITLE
how fix it

### ISSUE THREAD

**Issue by brafaz** [rbxb/place#6]
how fix it problem

WebSocket connection to 'wss://localhost/ws' failed:

**Comment by rbxb** [comment]
Do you have [LOCAL_MODE](https://github.com/rbxb/place/blob/3522d6fe97f3f7cef1518eeffb831732ca788655/web/root/place.js#L1) set to true?

**Comment by brafaz** [comment]
no,i not know it

**Comment by brafaz** [comment]
okey,it work ,sorry

**Comment by brafaz** [comment]
how set domine site my ip ?
