### ISSUE TITLE
Error Not Found

### ISSUE THREAD

**Issue by SozinV** [rbxb/place#7]
When connecting to the localhost to test it out it just says Not Found.

**Comment by rbxb** [comment]
What is the URL that is returning Not Found?

**Comment by SozinV** [comment]
Not really a URL, the page just says Not Found.

**Comment by rbxb** [comment]
Which page?

**Comment by SozinV** [comment]
When I just connect to the local host nothing loads, it just says Not Found.

**Comment by rbxb** [comment]
When you run the server from the command line make sure that you are running it from the same directory that the directory named "root" is in.

For example:
```
cd ./rbxb/place/web
place
```

Alternatively you can set the full filepath of the root directory when you run the server using the -root option.
For example:

```
place -root "C:/place/web/root"
```

Did this solve it?

**Comment by SozinV** [comment]
I'm confused, what is place suppose to represent because when I try to use what you put for setting up the root place isn't recognized as a command.

**Comment by rbxb** [comment]
Place is referring to this go program: https://github.com/rbxb/place/tree/master/cmd/place
How were you running the server before?

You can replace "place" in those examples with something like `go/bin/place` or path to wherever the compiled go program is.

**Comment by SozinV** [comment]
Okay, I see what you mean by the command -root doesn't work either. I might be that I'm missing something.

**Comment by rbxb** [comment]
What happens when you use -root with the path to the root directory?

**Comment by SozinV** [comment]
Like where I do cd "root folder" then use -root?

**Comment by rbxb** [comment]
Have you done both of these?
1. Installed the [Go Compiler](https://go.dev/)
2. Compiled [place](https://github.com/rbxb/place/tree/master/cmd/place) using the Go compiler

**Comment by SozinV** [comment]
I have installed Go Compiler, then from a video I watched I compiled main.go.

**Comment by rbxb** [comment]
Do you know the file path of the compiled program? It should be something like "C:/go/bin/place" but it will be different on your device. To run the program you will need to call it from the command line using that path. So you might run it like this:
```
C:/go/bin/place -root "C:/place/web/root"
```
