### ISSUE TITLE
Localhost says: Failed to connect.

### ISSUE THREAD

**Issue by Dolyfin** [rbxb/place#8]
After running place.exe in cmd. Going to localhost:8080 displays 'downloading map' with zoom buttons showing. After 1 second popup with "localhost says: Failed to connect. No fire wall, tried different ports with same problem
![image](https://user-images.githubusercontent.com/55581931/198978654-3f254bf7-def0-4960-84e7-060dff92f0f3.png)

**Comment by rbxb** [comment]
I just pushed a couple commits which may have fixed the issue.
