### ISSUE TITLE
Failed to connect

### ISSUE THREAD

**Issue by Malta112** [rbxb/place#9]
I compiled it on my ubuntu server and tried to connect to it but it just says Fails to connect but i see the downloading map
Another issue is there but no suggestion and he/she is using the localhost and I dont

**Comment by rbxb** [comment]
Can you look at the network tab in your browser and see if place.png is downloading successfully?  

Is the request to initiate the websocket connection failing? (look for a request to the path "ws")

Are there any errors outputted from any of the servers or in the browser console?

Does the server use HTTP or HTTPS?

**Comment by rbxb** [comment]
I just pushed a couple commits which may have fixed the issue.

**Comment by Malta112** [comment]
for me it is working now
